[package]
name = "api"
version = "0.1.0"
authors = ["m0ric <andreicristian6@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = {version = "0.3.12", features = ["ssl"] }
